### ISSUE TITLE
dynamic link ffmpeg .lib error

### ISSUE THREAD

**Issue by mingxingren** [zmwangx/rust-ffmpeg-sys#35]
I want to build this crate through dynamic link ffmpeg lib. but its error and  no detailed error message. I set FFMPEG_DIR Path and make 
statik false.  What should I do?

**Comment by mingxingren** [comment]
This system environment is window

**Comment by xs23933** [comment]
windows default build err nad not detailed error message

- vcpkg ffmpeg library
- windows 10

```rust
error: failed to run custom build command for `ffmpeg-sys-next v5.0.1`

Caused by:
  process didn't exit successfully: `\target\debug\build\ffmpeg-sys-next-47d089dc49f8a48a\build-script-build` (exit code: 101)
```

**Comment by mingxingren** [comment]
I suggest use dynamic ffmpeg librarys. because We need to control build config. So we just to generate blindings.rs.  need to modify the code in build.rs file. we need to add `FFMPEG_DIR` to environment variable to specify ffmpeg dll path. and bypass `CARGO_FEATURE_BUILD`  if judge
