### ISSUE TITLE
Support ffmpeg 5.0.0

### ISSUE THREAD

**Issue by svenstaro** [zmwangx/rust-ffmpeg-sys#36]
ffmpeg 5 has been released and I think this crate should support it. In Arch Linux, we're currently performing the ffmpeg 5 rebuild and we're getting blocked by Rust packages that need this crate.

Would be great if this crate could add support for that new ffmpeg release as otherwise we'd have to provide a compatibility build of ffmpeg.

**Comment by Polochon-street** [comment]
Hi,

I'm currently trying to make the crate work for ffmpeg 5.0.0. There's a slight problem wrt. libavresample that was apparently removed from 5.0.0 and onward, but other than that it should be doable.

**Comment by AdrianEddy** [comment]
I'm also interested in ffmpeg 5.0.0, looking forward to the updated Rust bindings

**Comment by Polochon-street** [comment]
I've made a first tentative PR that uses ffmpeg 5.0 on the CI, and the build finally turned green today (https://github.com/zmwangx/rust-ffmpeg/pull/90)
However, I've been a bit trigger-happy with the removal of deprecated functions, and I will have to fix that and some other stuff before releasing a new version

**Comment by Polochon-street** [comment]
Hi guys, I've published the new version, so ffmpeg-next should build for ffmpeg 5.0.

It has a few breaking changes seems upstream ffmpeg deleted some deprecated functions, but they should be documented in the `examples/`.

I'm closing this issue, but don't hesitate to report eventual bugs :)
