### ISSUE TITLE
wasm-pack build Err

### ISSUE THREAD

**Issue by niugm** [zmwangx/rust-ffmpeg-sys#8]
HI,guys,i try to use this crate with wasm-pack,when i run wasm-pack build,i got err like below:

-----------------------
 
 --- stdout
  cargo:rerun-if-env-changed=LIBAVUTIL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_wasm32-unknown-unknown
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_wasm32_unknown_unknown
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_wasm32-unknown-unknown
  cargo:rerun-if-env-changed=PKG_CONFIG_wasm32_unknown_unknown
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_wasm32-unknown-unknown
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_wasm32_unknown_unknown
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CrossCompilation', /Users/niugm/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg-sys-next-4.3.5/build.rs:700:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"

**Comment by zmwangx** [comment]
See my response on zmwangx/rust-ffmpeg: https://github.com/zmwangx/rust-ffmpeg/issues/40#issuecomment-729669609

**Comment by niugm** [comment]
> See my response on zmwangx/rust-ffmpeg: [zmwangx/rust-ffmpeg#40 (comment)](https://github.com/zmwangx/rust-ffmpeg/issues/40#issuecomment-729669609)

Thanks for the reply
